config/routes.rb
Rails.application.routes.draw do

  resources :memberships, only: [:index, :show, :new, :create, :edit, :update]
  resources :movies, only: [:index, :show, :new, :create, :edit, :update]
  resources :categories, only: [:index, :show, :new, :create, :edit, :update]
  resources :teams, only: [:index, :show, :new, :create, :edit, :update]
  resources  :movies, only: [:index, :show, :new, :create, :edit, :update]
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    resources :preferences, only: [:new, :index, :show, :create, :destroy]
  end

  delete 'users/:user_id/preferences/:id', to: 'preferences#destroy', as: 'delete_preferences'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movies
  has_many :preferences
  has_many :users, through: :preferences 
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team 
end

app/models/movie.rb
class Movie < ApplicationRecord
belongs_to :category





end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :user
  belongs_to :category 
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  def movie_fill
    allmovies = Movie.all
    vetocategories = []
    self.users.map do |user|
      user.preferences.map do |preference|
        if preference.like_or_dislike == "dislike"
          vetocategories << preference.category
          end
        end
      end
      allmovies.reject do |movie|
        vetocategories.include?(movie.category)
      end
    end


    # allmovies.delete_if do |movie|
    #     vetocategories.include?(movie.category)
    #   end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :teams, through: :memberships
  has_many :preferences
  has_many :categories, through: :preferences 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController


  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

#   Yt.configure do |config|
#   config.api_key = ENV["YOUTUBEAPIKEY"]
# end

# channel = Yt::Channel.new id: 'UClgRkhTL3_hImCAmdLfDE4g'

def index
# channel = Yt::Channel.new id: 'UCEC9pCgh1o7lVQ4BmzxFIaA'
@movies = Movie.all
end

def show
@movie = Movie.find(params[:id])
end

def new
end


end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def show
  end

  def index

    @user = User.find(params[:user_id])
    @user_preferences = @user.preferences
  end

  def new
    @user = User.find(params[:user_id])
    @preference = Preference.new(user_id: @user.id)
    @categories = Category.all
    @user_preferences = @user.preferences
  end

  def create

  @user = User.find(params[:user_id])
 @preference = Preference.create(preference_params)
 @user.preferences << @preference
 @user.save
 redirect_to user_preferences_path(@user)
  end

  def edit

  end

  def update

  end

  def destroy
    @user = User.find(params[:user_id])
    @user_preference = Preference.find(params[:id])
    @user_preference.delete
    redirect_to user_preferences_path(@user)
  end


private

def preference_params(*args)
params.require(:preference).permit(:like_or_dislike, :category_id)
end



end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

    def show
    @team = Team.find(params[:id])
    @users = @team.users
    @movie_options = @team.movie_fill
    end

    def index
    @teams = Team.all
    end

    def new
    @team = Team.new
    @users = User.all
    end

    def create

      @team = Team.create(team_params)
      redirect_to team_path(@team)
    end

    def edit
      @team = Team.find(params[:id])
    end
    #
    # def update
    # @team = Team.find(params[:id])
    # @team.update(team_params[:team_name])
    # redirect_to team_path(@team)
    # end

    def destroy
    end

    private

    def team_params(*args)
    params.require(:team).permit(:team_name, user_ids:[])
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  @user = User.find(params[:id])
  end

  def index
  @users = User.all
  end

  def new
  @user = User.new
  @teams = Team.all 
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
  @user.update(user_params(:username))
  redirect_to user_path(@user)
  end

  def destroy
  end

  private

  def user_params(*args)
  params.require(:user).permit(:username)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/index.erb
<% @movies.each do |movie|    %>
<p> <%= link_to(movie.name, movie_path(movie)) %> </p>
<% end %>

app/views/movies/show.erb
<h1> <%= @movie.name %> </h1>

app/views/preferences/index.erb
<h3> Back to: <%=link_to("Teams", teams_path) %>
<%=link_to("Users", users_path) %> </h3>

<h1> <%= @user.username.capitalize %>'s Movie Preferences: </h1>

<% @user_preferences.each do |preference|    %>
 <%= "#{@user.username.capitalize} #{preference.like_or_dislike.capitalize}s #{preference.category.name.capitalize}"   %>
 <br>
<%= button_to "delete", {action: "destroy", id: preference.id}, {method: :delete} %>
<br>
<% end %>


<br><br><br><br>
<p> <%= link_to("Add New Preference", new_user_preference_path(@user)) %> </p>

app/views/preferences/new.erb
<h3> Back to: <%=link_to("Teams", teams_path) %>
<%=link_to("Users", users_path) %> </h3>



<h2> <%= @user.username.capitalize %> - add new preference </h2>

<%=link_to("Back to My Preferences", user_preferences_path(@user)) %>


<br><br><br><br><br>

<h4> Add Preference: <h4>

<%= form_for([@user, @preference]) do |f| %>

<label>Type:</label>
<%= f.select(:like_or_dislike, ["like", "dislike"]) %>
<br><br>
<label>Catgory:</label>
<%= f.collection_select :category_id, @categories, :id, :name %>
<br><br>
   <%= f.submit "Add preference" %>
 <% end %>
</div>

app/views/users/index.erb
<h3> Back to: <%=link_to("Teams", teams_path) %>
<%=link_to("Users", users_path) %> </h3>

<% @users.each do |user|    %>
<p> <%= link_to(user.username, user_path(user)) %> </p>
<% end %>




<br><br><br><br>
<%=link_to("CREATE NEW USER", new_user_path) %>

app/views/users/new.erb
<h3> Back to: <%=link_to("Teams", teams_path) %>
<%=link_to("Users", users_path) %> </h3>

<%= form_for(@user) do |f| %>
  <label>User Name:</label><br>
  <%= f.text_field :username %><br>

<br>

  <label>Join Teams:</label> <br><br>
<%= f.collection_check_boxes :team_ids, @teams, :id, :team_name %><br>
<br><br>


  <%= f.submit %>
<% end %>

app/views/users/show.erb
<h3> Back to: <%=link_to("Teams", teams_path) %>
<%=link_to("Users", users_path) %> </h3>


<h1> <%= @user.username.capitalize %> </h1>

<p> <%= link_to("User Preferences", user_preferences_path(@user)) %> </p>


<br><br><br><br><br>
<p> <%= link_to("Back to all users", users_path) %> </p>